# Generated by Django 3.0.5 on 2022-12-09 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topic',
            new_name='item',
        ),
    ]
