# Generated by Django 3.0.5 on 2022-12-11 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
    ]
