# Generated by Django 3.0.5 on 2022-12-12 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0008_delete_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Topping',
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={},
        ),
    ]
