# Generated by Django 3.0.5 on 2022-12-12 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0009_auto_20221212_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='text',
            new_name='pizza_name',
        ),
    ]
