# Generated by Django 3.0.5 on 2022-12-12 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0010_auto_20221212_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='item',
            new_name='pizza',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='text',
            new_name='topping_name',
        ),
    ]
