# Generated by Django 3.0.5 on 2022-12-12 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0011_auto_20221212_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='pizza',
            new_name='item',
        ),
    ]
