# Generated by Django 3.0.5 on 2022-12-12 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0013_auto_20221212_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='text',
            new_name='topping_name',
        ),
    ]
